spring.application.name=JustDoItCloudPresentacion
spring.web.locale=es_CR
spring.web.locale-resolver=fixed

spring.sql.init.mode=always
spring.sql.init.platform=mysql
spring.sql.init.encoding=UTF-8

spring.datasource.url=jdbc:mysql://localhost:3306/justdoitdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=${DB_USR_NAME:justdoit}
spring.datasource.password=${DB_PWD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver